# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GradeGrubb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GradeGrubb
  pod 'Firebase/Core'
 pod 'Firebase'
 pod 'Firebase/Messaging'

 

  target 'GradeGrubbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GradeGrubb-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GradeGrubb-tvOS

  target 'GradeGrubb-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
